export default {
    today: [
        {
            name: 'Завтрак',
            data: [
                {
                    name: 'Каша овсянная',
                    weight: 50,
                    calory: 34,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Бананы',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Чай',
                    weight: 150,
                    calory: 34,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Бетерброды с сыром и маслом',
                    weight: 120,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
        {
            name: 'Обед',
            data: [
                {
                    name: 'Гороховый суп-пюре',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Хлеб ржаной',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Чай',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Шоколад молочный',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
        {
            name: 'Ужин',
            data: [
                {
                    name: 'Спагетти с сыром',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Хлеб ржаной',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Чай',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Халва',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
    ],
    tomorrow: [
        {
            name: 'Завтрак',
            data: [
                {
                    name: 'Каша гречневая',
                    weight: 80,
                    calory: 64,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Яблоки',
                    weight: 90,
                    calory: 144,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Какао',
                    weight: 50,
                    calory: 34,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Хлебцы ржаные',
                    weight: 60,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
        {
            name: 'Обед',
            data: [
                {
                    name: 'Уха',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Хлеб ржаной',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Чай',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Чак-чак',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
        {
            name: 'Перекус',
            data: [
                {
                    name: 'Курага',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Орехи грецкие',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
        {
            name: 'Ужин',
            data: [
                {
                    name: 'Плов',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Хлеб ржаной',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Чай',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
                {
                    name: 'Финики',
                    weight: 100,
                    calory: 134,
                    protein: '2.4',
                    fat: '1.4',
                    carbs: '12.4',
                },
            ],
        },
    ],
};
